adjective = input("please enter an adjective: ")
noun = input("please enter a noun: ")
verb = input("Please enter a verb ending in -ed: ")
animal = input("Please enter an animal: ")
print("Your Madlib:")
print("The", adjective, noun, verb, "over the lazy brown" ,animal)